### ISSUE TITLE
Allow client app to specify name/version

### ISSUE THREAD

**Issue by willsmythe** [LeanKit-Labs/vso-client#28]
If specified, pass this information in the user-agent string (along with whatever info the base library should pass). For example:

```
new client(url, creds, "myapp 1.0")
```

This may result in the following user-agent string in each request from the client:
```
user-agent: myapp 1.0; vso-client/1.0 node/10.0.3 windows
```

**Comment by reverentgeek** [comment]
This has been added to the latest client. You can specify a user-agent string with the options object passed when creating the client. The client constructor looks like:

    var vso = require('vso-client');
    var client = vso.createClient('url', 'collection', 'your-username', 'your-p@ssw0rd', {userAgent : "My App 1.0"});

The user agent string produced will look something like:

    user-agent: My App 1.0; vso-client/1.0 node/0.10.35 darwin
