### ISSUE TITLE
joinRoom method invoking put method with wrong arguments

### ISSUE THREAD

**Issue by bfcamara** [LeanKit-Labs/vso-client#30]
The joinRoom method is invoking the put method with wrong order in arguments 

Instead of 
```
@client.put path, @getOptions(), userId
```
it should be
```
@client.put path, userId, @getOptions()
```

**Comment by reverentgeek** [comment]
Thanks! That does appear to be the problem. I'll get a fix published soon.

**Comment by reverentgeek** [comment]
I pushed v0.2.5 to npm. Let me know if that resolves the issue.

**Comment by bfcamara** [comment]
Thank you @reverentgeek for the fix. It's working now.
