### ISSUE TITLE
Build 2.0 

### ISSUE THREAD

**Issue by lszomoru** [LeanKit-Labs/vso-client#32]
Are there any plans to add support for [build 2.0](https://www.visualstudio.com/integrate/api/build/overview)? 
If you accept contributions I am more than happy to submit a pull request.

**Comment by reverentgeek** [comment]
Yes, pull requests are accepted! However, I believe Microsoft now has an official VSO (or VSTS?) [node client](https://www.npmjs.com/package/vso-node-api). You may want to see if it supports the latest build API.

**Comment by lszomoru** [comment]
thanks! I will check it out.

**Comment by lszomoru** [comment]
It does look like the official node client does support build 2.0. Closing this issue.
